In [4]:
import pandas as pd 
import numpy as np

In [5]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [6]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
#dataframing

In [8]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Bengaloru', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age       City  Salary
0   John   28   New York   65000
1   Anna   34      Paris   70000
2  Peter   29  Bengaloru   62000
3  Linda   42     London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df2[['Name','Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [11]:
df2['new']=[1,2,3,'hi']
df2

    Name  Age      City  Salary new
0   John   28  New York   65000   1
1   Anna   34     Paris   70000   2
2  Peter   29    Berlin   62000   3
3  Linda   42    London   85000  hi

In [17]:
df2.drop('new',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000